// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.Infrastructure.Database;

namespace eShop.Infrastructure.Migrations
{
    [DbContext(typeof(eShopDbContext))]
    partial class eShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("eShop.Entities.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Category One"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Category Two"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Category Three"
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.HasKey("DayId");

                    b.HasIndex("WeekId");

                    b.ToTable("Day");

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            DayOfWeek = 1,
                            WeekId = 1
                        },
                        new
                        {
                            DayId = 2,
                            DayOfWeek = 1,
                            WeekId = 2
                        },
                        new
                        {
                            DayId = 3,
                            DayOfWeek = 1,
                            WeekId = 3
                        },
                        new
                        {
                            DayId = 4,
                            DayOfWeek = 1,
                            WeekId = 4
                        },
                        new
                        {
                            DayId = 5,
                            DayOfWeek = 1,
                            WeekId = 5
                        },
                        new
                        {
                            DayId = 6,
                            DayOfWeek = 1,
                            WeekId = 6
                        },
                        new
                        {
                            DayId = 7,
                            DayOfWeek = 1,
                            WeekId = 7
                        },
                        new
                        {
                            DayId = 8,
                            DayOfWeek = 1,
                            WeekId = 8
                        },
                        new
                        {
                            DayId = 9,
                            DayOfWeek = 1,
                            WeekId = 9
                        },
                        new
                        {
                            DayId = 10,
                            DayOfWeek = 1,
                            WeekId = 10
                        },
                        new
                        {
                            DayId = 11,
                            DayOfWeek = 1,
                            WeekId = 11
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("HowToGo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighlightedEvent")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TeachersId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://www.nhm.ac.uk/content/dam/nhmwww/visit/Exhibitions/events/after-hours/silent-disco/silent-disco-calendar.jpg",
                            InStock = true,
                            IsHighlightedEvent = true,
                            LocationId = 1,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event One",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 1
                        },
                        new
                        {
                            EventId = 2,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://i.ytimg.com/vi/5Cy_KvI2nME/maxresdefault.jpg",
                            InStock = true,
                            IsHighlightedEvent = true,
                            LocationId = 2,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Two",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 2
                        },
                        new
                        {
                            EventId = 3,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://www.nhm.ac.uk/content/dam/nhmwww/visit/Exhibitions/events/after-hours/silent-disco/silent-disco-calendar.jpg",
                            InStock = true,
                            IsHighlightedEvent = false,
                            LocationId = 3,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Three",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 2
                        },
                        new
                        {
                            EventId = 4,
                            CategoryId = 2,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://i.ytimg.com/vi/5Cy_KvI2nME/maxresdefault.jpg",
                            InStock = true,
                            IsHighlightedEvent = true,
                            LocationId = 4,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Four",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 2
                        },
                        new
                        {
                            EventId = 5,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://www.nhm.ac.uk/content/dam/nhmwww/visit/Exhibitions/events/after-hours/silent-disco/silent-disco-calendar.jpg",
                            InStock = true,
                            IsHighlightedEvent = false,
                            LocationId = 5,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Five",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 2
                        },
                        new
                        {
                            EventId = 6,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://i.ytimg.com/vi/5Cy_KvI2nME/maxresdefault.jpg",
                            InStock = true,
                            IsHighlightedEvent = false,
                            LocationId = 6,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Six",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 3
                        },
                        new
                        {
                            EventId = 7,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://www.nhm.ac.uk/content/dam/nhmwww/visit/Exhibitions/events/after-hours/silent-disco/silent-disco-calendar.jpg",
                            InStock = true,
                            IsHighlightedEvent = false,
                            LocationId = 7,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Seven",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 3
                        },
                        new
                        {
                            EventId = 8,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://i.ytimg.com/vi/5Cy_KvI2nME/maxresdefault.jpg",
                            InStock = true,
                            IsHighlightedEvent = false,
                            LocationId = 8,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Eight",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 3
                        },
                        new
                        {
                            EventId = 9,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://www.nhm.ac.uk/content/dam/nhmwww/visit/Exhibitions/events/after-hours/silent-disco/silent-disco-calendar.jpg",
                            InStock = true,
                            IsHighlightedEvent = true,
                            LocationId = 9,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Nine",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 3
                        },
                        new
                        {
                            EventId = 10,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://i.ytimg.com/vi/5Cy_KvI2nME/maxresdefault.jpg",
                            InStock = true,
                            IsHighlightedEvent = false,
                            LocationId = 10,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Ten",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 3
                        },
                        new
                        {
                            EventId = 11,
                            CategoryId = 1,
                            Currency = 0,
                            HowToGo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.",
                            ImageUrl = "https://www.nhm.ac.uk/content/dam/nhmwww/visit/Exhibitions/events/after-hours/silent-disco/silent-disco-calendar.jpg",
                            InStock = true,
                            IsHighlightedEvent = true,
                            LocationId = 11,
                            LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Name = "Event Eleven",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum",
                            TeachersId = 3
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 1,
                            ZipCode = 12345
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 2,
                            ZipCode = 12346
                        },
                        new
                        {
                            LocationId = 3,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 3,
                            ZipCode = 12347
                        },
                        new
                        {
                            LocationId = 4,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 4,
                            ZipCode = 12348
                        },
                        new
                        {
                            LocationId = 5,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 5,
                            ZipCode = 12349
                        },
                        new
                        {
                            LocationId = 6,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 6,
                            ZipCode = 12350
                        },
                        new
                        {
                            LocationId = 7,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 7,
                            ZipCode = 12351
                        },
                        new
                        {
                            LocationId = 8,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 8,
                            ZipCode = 12352
                        },
                        new
                        {
                            LocationId = 9,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 9,
                            ZipCode = 12353
                        },
                        new
                        {
                            LocationId = 10,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 10,
                            ZipCode = 12354
                        },
                        new
                        {
                            LocationId = 11,
                            City = "Stockholm län",
                            State = "Stockholm",
                            Street = "vägen",
                            StreetNumber = 11,
                            ZipCode = 12355
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DanceLevel")
                        .HasColumnType("int");

                    b.Property<int>("DanceRole")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotalEUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderTotalSEK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eShop.Entities.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("eShop.Entities.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EventId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            EventId = 1
                        },
                        new
                        {
                            ScheduleId = 2,
                            EventId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            EventId = 3
                        },
                        new
                        {
                            ScheduleId = 4,
                            EventId = 4
                        },
                        new
                        {
                            ScheduleId = 5,
                            EventId = 5
                        },
                        new
                        {
                            ScheduleId = 6,
                            EventId = 6
                        },
                        new
                        {
                            ScheduleId = 7,
                            EventId = 7
                        },
                        new
                        {
                            ScheduleId = 8,
                            EventId = 8
                        },
                        new
                        {
                            ScheduleId = 9,
                            EventId = 9
                        },
                        new
                        {
                            ScheduleId = 10,
                            EventId = 10
                        },
                        new
                        {
                            ScheduleId = 11,
                            EventId = 11
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("EventId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("eShop.Entities.Entities.Teachers", b =>
                {
                    b.Property<int>("TeachersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeachingAssistantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeachersId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeachersId = 1,
                            TeacherName = "Teacher One",
                            TeachingAssistantName = "Teaching Assistant One"
                        },
                        new
                        {
                            TeachersId = 2,
                            TeacherName = "Teacher Two",
                            TeachingAssistantName = "Teaching Assistant Two"
                        },
                        new
                        {
                            TeachersId = 3,
                            TeacherName = "Teacher Three",
                            TeachingAssistantName = "Teaching Assistant Three"
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("TicketName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalAvailableTicket")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("EventId");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 1,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 2,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 1,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 3,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 1,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 4,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 2,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 5,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 2,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 6,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 3,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 7,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 3,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 8,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 4,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 9,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 4,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 10,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 5,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 11,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 5,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 12,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 5,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 13,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 6,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 14,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 6,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 15,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 7,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 16,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 7,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 17,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 8,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 18,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 8,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 19,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 9,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 20,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 9,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 21,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 10,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        },
                        new
                        {
                            TicketId = 22,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 10,
                            TicketName = "Ticket One",
                            TicketPrice = 50m,
                            TotalAvailableTicket = 10
                        },
                        new
                        {
                            TicketId = 23,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 11,
                            TicketName = "Ticket Two",
                            TicketPrice = 100m,
                            TotalAvailableTicket = 20
                        },
                        new
                        {
                            TicketId = 24,
                            Description = "Omnis et enim aperiam inventore",
                            EventId = 11,
                            TicketName = "Ticket Three",
                            TicketPrice = 150m,
                            TotalAvailableTicket = 15
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Times", b =>
                {
                    b.Property<int>("TimesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("TimesId");

                    b.HasIndex("DayId");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimesId = 1,
                            DayId = 1,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(1324),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 357, DateTimeKind.Local).AddTicks(952)
                        },
                        new
                        {
                            TimesId = 2,
                            DayId = 2,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3040),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3008)
                        },
                        new
                        {
                            TimesId = 3,
                            DayId = 3,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3100),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3095)
                        },
                        new
                        {
                            TimesId = 4,
                            DayId = 4,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3132),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3128)
                        },
                        new
                        {
                            TimesId = 5,
                            DayId = 5,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3161),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3157)
                        },
                        new
                        {
                            TimesId = 6,
                            DayId = 6,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3194),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3190)
                        },
                        new
                        {
                            TimesId = 7,
                            DayId = 7,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3222),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3218)
                        },
                        new
                        {
                            TimesId = 8,
                            DayId = 8,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3251),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3247)
                        },
                        new
                        {
                            TimesId = 9,
                            DayId = 9,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3278),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3275)
                        },
                        new
                        {
                            TimesId = 10,
                            DayId = 10,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3309),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3305)
                        },
                        new
                        {
                            TimesId = 11,
                            DayId = 11,
                            TimeEnd = new DateTime(2020, 7, 8, 21, 15, 42, 360, DateTimeKind.Local).AddTicks(3337),
                            TimeStart = new DateTime(2020, 7, 8, 19, 15, 42, 360, DateTimeKind.Local).AddTicks(3333)
                        });
                });

            modelBuilder.Entity("eShop.Entities.Entities.Week", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("WeekId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Week");

                    b.HasData(
                        new
                        {
                            WeekId = 1,
                            ScheduleId = 1
                        },
                        new
                        {
                            WeekId = 2,
                            ScheduleId = 2
                        },
                        new
                        {
                            WeekId = 3,
                            ScheduleId = 3
                        },
                        new
                        {
                            WeekId = 4,
                            ScheduleId = 4
                        },
                        new
                        {
                            WeekId = 5,
                            ScheduleId = 5
                        },
                        new
                        {
                            WeekId = 6,
                            ScheduleId = 6
                        },
                        new
                        {
                            WeekId = 7,
                            ScheduleId = 7
                        },
                        new
                        {
                            WeekId = 8,
                            ScheduleId = 8
                        },
                        new
                        {
                            WeekId = 9,
                            ScheduleId = 9
                        },
                        new
                        {
                            WeekId = 10,
                            ScheduleId = 10
                        },
                        new
                        {
                            WeekId = 11,
                            ScheduleId = 11
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.Day", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Week", "Week")
                        .WithMany("Day")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.Event", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.Entities.Teachers", "Teachers")
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.OrderDetail", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.Schedule", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Event", "Event")
                        .WithMany("Schedule")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("eShop.Entities.Entities.Ticket", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.Times", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Day", "Day")
                        .WithMany("Times")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Entities.Week", b =>
                {
                    b.HasOne("eShop.Entities.Entities.Schedule", "Schedule")
                        .WithMany("Week")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
